apiVersion: apps/v1
kind: Deployment
metadata:
  name: resilience-platform-deployment
  namespace: resilience-platform
  labels:
    app: resilience-platform 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resilience-platform 
  template:
    metadata:
      labels:
        app: resilience-platform
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 30001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: fastapi-container
        image: ghcr.io/illahristuk-del/circuit-breaker-manager:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: platform-config
        livenessProbe:
          httpGet: {path: /, port: 8000}
          initialDelaySeconds: 15
        readinessProbe:
          httpGet: {path: /, port: 8000}
          initialDelaySeconds: 5
        resources:
          limits: {cpu: "500m", memory: "512Mi"}
          requests: {cpu: "250m", memory: "256Mi"}
      volumes:
      - name: secret-volume
        secret:
          secretName: platform-secret