"""fix_service_id_typo

Revision ID: a2124dc87ef0
Revises: ac70e14fece6
Create Date: 2026-05-24 01:10:11.974087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2124dc87ef0'
down_revision: Union[str, Sequence[str], None] = 'ac70e14fece6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuit_breaker_state_logs', sa.Column('service_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('circuit_breaker_state_logs_sercives_id_fkey'), 'circuit_breaker_state_logs', type_='foreignkey')
    op.create_foreign_key(None, 'circuit_breaker_state_logs', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_column('circuit_breaker_state_logs', 'sercives_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuit_breaker_state_logs', sa.Column('sercives_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'circuit_breaker_state_logs', type_='foreignkey')
    op.create_foreign_key(op.f('circuit_breaker_state_logs_sercives_id_fkey'), 'circuit_breaker_state_logs', 'services', ['sercives_id'], ['id'], ondelete='CASCADE')
    op.drop_column('circuit_breaker_state_logs', 'service_id')
    # ### end Alembic commands ###
