"""initial_migration

Revision ID: ac70e14fece6
Revises: 
Create Date: 2026-05-24 01:02:30.468515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac70e14fece6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CLOSED', 'OPEN', 'HALF_OPEN', name='taskstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('circuit_breaker_state_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sercives_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.Enum('CLOSED', 'OPEN', 'HALF_OPEN', name='taskstatus'), nullable=False),
    sa.Column('to_state', sa.Enum('CLOSED', 'OPEN', 'HALF_OPEN', name='taskstatus'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sercives_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_check_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sevice_id', sa.Integer(), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sevice_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_check_log')
    op.drop_table('circuit_breaker_state_logs')
    op.drop_table('services')
    # ### end Alembic commands ###
